### ISSUE TITLE
Compile CUASM error

### ISSUE THREAD

**Issue by xiaoyu1004** [cloudcores/CuAssembler#9]
![image](https://user-images.githubusercontent.com/80047235/187599044-0ab04a2c-5667-475c-8f0a-d9b53af5ca3f.png)

**Comment by cloudcores** [comment]
This version does not support volta(sm70) yet.

For a quick work around, copy the file `DefaultInsAsmRepos.sm_75.txt` in directory `InsAsmRepos` to `DefaultInsAsmRepos.sm_70.txt`, although there may be a lot of bugs.

It is planned to release a new version with better support for sm70/75/80/86 recently.
